# Generated by Django 3.0.7 on 2021-01-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('note', models.TextField()),
                ('archive', models.IntegerField(default='0')),
            ],
        ),
    ]
